// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetArtistsUsernameRequest struct {
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

// GetArtistsUsername400ApplicationJSON - Invalid request
type GetArtistsUsername400ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

// GetArtistsUsername200ApplicationJSON - Successfully returned an artist
type GetArtistsUsername200ApplicationJSON struct {
	AlbumsRecorded *int64  `json:"albums_recorded,omitempty"`
	ArtistGenre    *string `json:"artist_genre,omitempty"`
	ArtistName     *string `json:"artist_name,omitempty"`
}

type GetArtistsUsernameResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully returned an artist
	GetArtistsUsername200ApplicationJSONObject *GetArtistsUsername200ApplicationJSON
	// Invalid request
	GetArtistsUsername400ApplicationJSONObject *GetArtistsUsername400ApplicationJSON
}
