// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetArtistsRequest struct {
	// Limits the number of items on a page
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Specifies the page number of the artists to be displayed
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *GetArtistsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetArtistsRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type ResponseBody struct {
	AlbumsRecorded *int64  `json:"albums_recorded,omitempty"`
	ArtistGenre    *string `json:"artist_genre,omitempty"`
	ArtistName     *string `json:"artist_name,omitempty"`
	Username       string  `json:"username"`
}

func (o *ResponseBody) GetAlbumsRecorded() *int64 {
	if o == nil {
		return nil
	}
	return o.AlbumsRecorded
}

func (o *ResponseBody) GetArtistGenre() *string {
	if o == nil {
		return nil
	}
	return o.ArtistGenre
}

func (o *ResponseBody) GetArtistName() *string {
	if o == nil {
		return nil
	}
	return o.ArtistName
}

func (o *ResponseBody) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

type GetArtistsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully returned a list of artists
	Classes []ResponseBody
}

func (o *GetArtistsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetArtistsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetArtistsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetArtistsResponse) GetClasses() []ResponseBody {
	if o == nil {
		return nil
	}
	return o.Classes
}
