// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetArtistsRequest struct {
	// Limits the number of items on a page
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Specifies the page number of the artists to be displayed
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// GetArtists400ApplicationJSON - Invalid request
type GetArtists400ApplicationJSON struct {
	Message *string `json:"message,omitempty"`
}

type GetArtists200ApplicationJSON struct {
	AlbumsRecorded *int64  `json:"albums_recorded,omitempty"`
	ArtistGenre    *string `json:"artist_genre,omitempty"`
	ArtistName     *string `json:"artist_name,omitempty"`
	Username       string  `json:"username"`
}

type GetArtistsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successfully returned a list of artists
	GetArtists200ApplicationJSONObjects []GetArtists200ApplicationJSON
	// Invalid request
	GetArtists400ApplicationJSONObject *GetArtists400ApplicationJSON
}
