// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetArtistsUsernameRequest struct {
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

func (o *GetArtistsUsernameRequest) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

// GetArtistsUsernameResponseBody - Successfully returned an artist
type GetArtistsUsernameResponseBody struct {
	AlbumsRecorded *int64  `json:"albums_recorded,omitempty"`
	ArtistGenre    *string `json:"artist_genre,omitempty"`
	ArtistName     *string `json:"artist_name,omitempty"`
}

func (o *GetArtistsUsernameResponseBody) GetAlbumsRecorded() *int64 {
	if o == nil {
		return nil
	}
	return o.AlbumsRecorded
}

func (o *GetArtistsUsernameResponseBody) GetArtistGenre() *string {
	if o == nil {
		return nil
	}
	return o.ArtistGenre
}

func (o *GetArtistsUsernameResponseBody) GetArtistName() *string {
	if o == nil {
		return nil
	}
	return o.ArtistName
}

type GetArtistsUsernameResponse struct {
	// Successfully returned an artist
	TwoHundredApplicationJSONObject *GetArtistsUsernameResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetArtistsUsernameResponse) GetTwoHundredApplicationJSONObject() *GetArtistsUsernameResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *GetArtistsUsernameResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetArtistsUsernameResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetArtistsUsernameResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
