// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// PostArtistsResponseBody - Invalid request
type PostArtistsResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &PostArtistsResponseBody{}

func (e *PostArtistsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
